README.md

me bota nessa brincadeira ai

---

README.md

add: vitucordeiro -> @dopplervicor

---

README.md

Vou de PHP com Swoole/Swow no Hyperf.

Quero brincar também

---

README.md

Salve! Ideia muito top! Gostaria de participar.

Adiciona Participante Cristiano Cunha

---

README.md

Gostaria de participar porque nunca fiz algo para ser testado assim e com mais pessoas participando e ajudando, acho que será bem divertido. Espero poder colaborar nas APIs e aprender bastante. 😊

Add @kauefraga

---

README.md

Nova inscrição @natanaelsimoes

---

participantes/dupla-de-2/README.md
participantes/dupla-de-2/docker-compose.yml
participantes/dupla-de-2/nginx.conf

Add Dupla de 2 team

---

participantes/Bandolin/README.md

Email adicionado ao readme.md.
Erro ao executar as migrations foi corrigido, o processo de build deve funcionar perfeitamente agora.

Updated readme.md

---

participantes/lazaronixon/README.md
participantes/lazaronixon/docker-compose.yml

Estou removendo o cache e ajustando cpu e memory, a imagem foi atualizada tambem.

lazaronixon update

---

README.md
participantes/MrPowerGamerBR/README.md
participantes/MrPowerGamerBR/docker-compose.yml
participantes/MrPowerGamerBR/nginx.conf

Como o título diz: É uma implementação... mas não quer dizer que é bem feita xd.
Uma implementação em Kotlin, bem simples, feita em algumas horinhas pois eu achei a ideia muito legal.
(A única coisa que eu "propositalmente" não implementei, foi a parte de retornar Bad Request caso o JSON esteja sinteticamente incorreto, pois infelizmente tentar verificar a diferença entre "o nome é null então isso deve ser um Unprocessable Entity" e verificar "o nome é um número então isso deve ser um Bad Request" é difícil pelo kotlinx.serialization, já que ele acaba retornando a mesma exception independentemente de qual foi o problema na hora de deserializar o JSON, então qualquer problema no JSON ou nos requisitos dão Unprocessable Entity)
(Aliás, não sei se era para eu incluir o meu nome na tabela de …

Add my own (hacky) implementation

---

README.md
participantes/isaacnborges/README.md
participantes/isaacnborges/docker-compose.yml
participantes/isaacnborges/nginx.conf

add isaacnborges project

---

participantes/viniciusfonseca/README.md
participantes/viniciusfonseca/docker-compose.yml
participantes/viniciusfonseca/nginx.conf

Bora botar o caranguejo pra apanhar!

add viniciusfonseca submission

---

participantes/h4nkb31f0ng/README.md
participantes/h4nkb31f0ng/docker-compose.yml
participantes/h4nkb31f0ng/nginx.conf
participantes/h4nkb31f0ng/schema.sql

[Repositório](https://github.com/leorcvargas/rinha-de-backend-2023-q3)
- Go 1.21
- [Gin](https://github.com/gin-gonic/gin) (HTTP framework)
- [Fx](https://github.com/uber-go/fx) (DI framework)
- Postgres
- Nginx
- [Twitter](https://twitter.com/h4nkb31f0ng)
- [LinkedIn](https://www.linkedin.com/in/leonardo-vargas-6a2216116/)

Participante h4nkb31f0ng 

---

participantes/hampshire/README.md
participantes/hampshire/docker-compose.yml
participantes/hampshire/nginx.conf
participantes/rode/README.md
participantes/rode/docker-compose.yml
participantes/rode/nginx.conf

add rode and hampshire

---

participantes/luucaspole/README.md
participantes/luucaspole/docker-compose.yml
participantes/luucaspole/nginx.conf

Github: https://github.com/lukas8219
Twitter/X: https://twitter.com/luucaspole
Project Url: https://github.com/lukas8219/rinha-be-2023-q3
- NodeJS/ExpressJS
- Postgres
- Redis

feat(inscrição): @luucaspole - nodejs/postgres/redis

---

participantes/lauroappelt/README.md
participantes/lauroappelt/docker-compose.yml
participantes/lauroappelt/docker/nginx/nginx.conf

Entrega esquenta - rinha backend

add readme docker-compose nginx conf

---

participantes/lazaronixon/docker-compose.yml
participantes/lazaronixon/nginx.conf

update lazaronixon 2

---

participantes/Bandolin/docker-compose.yml
participantes/Bandolin/nginx.conf
participantes/Bandolin/www.conf

Bugs encontrados na aplicação foram corrigidos.
Foram adicionadas otimizações na aplicação para ajudar com o desempenho.
nginx.conf e www.conf foram adicionados ao projeto para que outras pessoas possam ver facilmente.
Será necessário apagar as imagens locais e recriar as mesmas para que as alterações tenham efeito.

Atualização da aplicação

---

participantes/isaacnborges/README.md
participantes/isaacnborges/docker-compose.yml
participantes/isaacnborges/nginx.conf

não ta extraordinario, mas melhorou legal desde a ultima

update rinha configurations

---

participantes/leandronsp/README.md
participantes/leandronsp/docker-compose.yml
participantes/leandronsp/init.sql
participantes/leandronsp/nginx.conf

Bora colocar o Ruby na rinha também.
* Ruby 3.2 [+YJIT](https://shopify.engineering/ruby-yjit-is-production-ready)
* PostgreSQL
* NGINX

A wild Ruby appears

---

participantes/thelinuxlich/bootstrap.sql
participantes/thelinuxlich/docker-compose.yml
participantes/thelinuxlich/nginx.conf

Tive que fazer algumas alterações mas agora fechou

últimos fixes, prometo!

---

participantes/kalogs-c/README.md
participantes/kalogs-c/docker-compose.yml
participantes/kalogs-c/init.sql

fix: participant kalogs-c init.sql

---

participantes/Tagliatti/README.md
participantes/Tagliatti/database.sql
participantes/Tagliatti/docker-compose.yaml
participantes/Tagliatti/nginx.conf

Adicionado participação @Tagliatti

Participação Tagliatti

---

participantes/flavio1110/README.md
participantes/flavio1110/docker-compose.yml
participantes/flavio1110/initdb.sql
participantes/flavio1110/nginx.conf

Github: [@flavio1110](https://github.com/flavio1110)
Twitter: [@flavio1110](https://twitter.com/flavio1110)
Repo: <https://github.com/flavio1110/rinha-de-backend-2023-q3>
--- 
Eu vou provavelmente precisar atualizar depois, mas deixa pelo menos essa versão garantida :kek.

Add flavio1110 participant

---

participantes/lpicanco/README.md
participantes/lpicanco/docker-compose.yml
participantes/lpicanco/nginx.conf
participantes/lpicanco/schema.sql

Add lpicanco

---

participantes/EuFountai/docker-compose.yml
participantes/EuFountai/init.sql
participantes/EuFountai/nginx.conf

tentando manejar melhor a memoria e as conexões

chore(update): Update EuFountai project configs

---

participantes/andrew-vasco/docker-compose.yaml

Ajusta para buscar imagem no docker hub.

fix - altera para buscar imagem no docker hub

---

participantes/LuisKpBeta/README.md
participantes/LuisKpBeta/db/seed.sql
participantes/LuisKpBeta/docker-compose.yml
participantes/LuisKpBeta/nginx.conf

adicionando participação vulgokpbeta v1

---

participantes/vimsos/README.md
participantes/vimsos/config/migrations/01_person_table.sql
participantes/vimsos/config/nginx.conf
participantes/vimsos/docker-compose.yml

submissão vimsos

---

participantes/brunoborges/ddl.sql
participantes/brunoborges/docker-compose-arm.yml
participantes/brunoborges/docker-compose.yml
participantes/brunoborges/nginx.conf
participantes/brunoborges/run.sh

Submission by brunoborges

---

participantes/willy-r/README.md
participantes/willy-r/docker-compose.yml
participantes/willy-r/nginx.conf

Add willy-r participant

---

participantes/bpaulino0/README.md
participantes/bpaulino0/docker-compose.yml
participantes/bpaulino0/nginx.conf

Olá Francisco!
To acompanhando a Rinha de backend no Twitter e resolvi participar contribuindo com uma aplicação usando Elixir :) 
Ta aqui o meu PR. Qualquer coisa, estou a disposição.
Repo do projeto: [https://github.com/brunojppb/rinha-backend-2023-q3-elixir](https://github.com/brunojppb/rinha-backend-2023-q3-elixir)
Disponível [aqui](https://github.com/brunojppb/rinha-de-backend-2023-q3/tree/participante-bpaulino0/participantes/bpaulino0), mas aqui vai um screenshot pra facilitar:

Adiciona bpaulino como participante usando Elixir

---

participantes/OpenCodeCo/README.md
participantes/OpenCodeCo/docker-compose.yml
participantes/OpenCodeCo/migrations.sql
participantes/OpenCodeCo/nginx.conf

Participação da OpenCodeCo com Swoole & Hyperf.
Repositório do projeto: https://github.com/opencodeco/rinha-de-backend-2023-q3

Participação da OpenCodeCo com Swoole & Hyperf na Rinha

---

participantes/flavio1110/docker-compose.yml
participantes/flavio1110/initdb.sql

Reajustando os recursos e o startup.
[Resultado está legal.](https://fsilva.me/rinha-de-backend/rinhabackendsimulation-20230821080703643/)

Rebalance resources on compose file and tweak startup

---

participantes/met4tron/docker-compose.yml
participantes/met4tron/init.sql
participantes/met4tron/nginx.conf
participantes/met4tron/readme.md

Me adicionando como participante :)

chore: add participant

---

participantes/igorsantos07/README.md
participantes/igorsantos07/docker-compose.yml

Na dúvida se vai dar ruim simplesmente pq eu to retornando 422 em qualquer erro de validação (ao invés do requisito de 400 em casos especiais) kkkry

Adicionando participante igorsantos07

---

participantes/navarro/README.md
participantes/navarro/db.sql
participantes/navarro/docker-compose.yml
participantes/navarro/nginx.conf

Galo velho porém experiente =p

Inscreve o galo do Navarro

---

participantes/fabricio_juliatto/README.md
participantes/fabricio_juliatto/docker-compose.yml
participantes/fabricio_juliatto/nginx.conf

Segue a minha submissão galera. Valeu!

Adicionar participante Fabricio Juliatto/@VFabricio

---

participantes/leandronsp/README.md
participantes/leandronsp/docker-compose.yml
participantes/leandronsp/init.sql
participantes/leandronsp/postgresql.conf

Atualização do README, docker compose e outras configurações.

Atualizar versão Ruby do leandronsp

---

.github/workflows/pr.yml

A raiva que eu to dessa joça que funfa no `act` mas não funfa aqui

Fix workflow PR

---

participantes/rwillians/docker-compose.yml
participantes/rwillians/nginx.conf
participantes/rwillians/start

Perae que eu to aproveitando pra testar uma workflow

Participante @rwillians_

---

participantes/lucasmadeira/README.md
participantes/lucasmadeira/docker-compose.yml
participantes/lucasmadeira/nginx.conf

Participação com SpringBoot e Postgres, se não rodar camarada pode fechar o PR, parabéns pela iniciativa, deu para aprender bastante

Participação Lucas Madeira

---

participantes/fernandozanutto/docker-compose.yml
participantes/fernandozanutto/nginx.conf

atualizacao nginxg e docker-compose

---

participantes/true_eduardo/README.md
participantes/true_eduardo/docker-compose.yml
participantes/true_eduardo/initdb.sql
participantes/true_eduardo/nginx.conf

Segue a minha contribuição para a rinha de backend

o Destemido Gopher

---

participantes/insalubre/README.MD
participantes/insalubre/docker-compose.yml
participantes/insalubre/nginx.conf
participantes/insalubre/schema.sql

adicionando [@_insalubre](https://twitter.com/_insalubre) na rinha
acredito que seja o primeiro projeto em Vlang

Add insalubre

---

participantes/felipemarkson/README.md
participantes/felipemarkson/deletevolume.sh
participantes/felipemarkson/docker-compose.yml
participantes/felipemarkson/nginx.conf

Utilizo nessa participação apenas C, nada mais, nada menos :P. (Até o banco de dados é compilado)

API in pure C

---

participantes/vhogemann/README.md
participantes/vhogemann/bootstrap.sql
participantes/vhogemann/docker-compose.yml
participantes/vhogemann/nginx.conf

Victor Hogemann
- Github: [vhogemann](https://github.com/vhogemann)
- Twitter: [vhogeman](https://twitter.com/vhogemann)
- Mastodon: [vhogemann](https://mastodon.sdf.org/@vhogemann)
- Repo: [vhogemann/rinha-de-backend-2023](https://github.com/vhogemann/rinha-de-backend-2023)
Stack
- [NET 7.0](https://dotnet.microsoft.com/)
- [F#](https://fsharp.org/)
- [Falco](https://www.falcoframework.com/)
- [Donald](https://github.com/pimbrouwers/Donald)
- [Npgsql](https://www.npgsql.org/)

vhogemann - F# NET 7.0

---

participantes/matheuslc/README.md
participantes/matheuslc/docker-compose.yml
participantes/matheuslc/init.sql
participantes/matheuslc/nginx.conf
participantes/matheuslc/postgresql.conf

Adicionando minha participação à rinha! 
Mais um projetinho em Golang

Add matheuslc

---

participantes/navarro-touche/README.md
participantes/navarro-touche/db.sql
participantes/navarro-touche/docker-compose.yml
participantes/navarro-touche/nginx.conf
participantes/navarro/README.md
participantes/navarro/nginx.conf

Como eu acabei fazendo uma implementação com uma outra lib http (bem obscura e de autoria própria inclusive hehehe), resolvi colocar ela pra rinha tmb!
No MR vai micro ajustes na minha outra participação tmb.

Inclui meu segundo galo

---

participantes/Bandolin_simplified_api/README.md
participantes/Bandolin_simplified_api/docker-compose.yml
participantes/Bandolin_simplified_api/my.cnf
participantes/Bandolin_simplified_api/nginx.conf
participantes/Bandolin_simplified_api/www.conf

Novo projeto PHP sem frameworks

Added new project to the competition

---

participantes/andrelsmelo/nginx.conf

TInha zuado a porta de entrada, agora (A principio) funciona

Tinha colocado a porta errada no nginx.conf

---

participantes/h4ad/README.md
participantes/h4ad/default.conf
participantes/h4ad/docker-compose.yml
participantes/h4ad/init.sql
participantes/h4ad/postgresql.conf

Olá, eis minha participação usando uma API em Golang.

Participante h4ad

---

participantes/guimeira/README.md
participantes/guimeira/docker-compose.yml
participantes/guimeira/nginx.conf

Obrigado por animarem a bolha dev nessas últimas semanas! :heart:

Guilherme Meira (guimeira): Java + Quarkus + Postgres

---

participantes/juniorleaoo/README.md
participantes/juniorleaoo/docker-compose.yml
participantes/juniorleaoo/nginx.conf
participantes/juniorleaoo/schema.sql

add @juniorleaoo 

---

participantes/lucasraziel/README.md
participantes/lucasraziel/docker-compose.yml
participantes/lucasraziel/nginx.conf

Github: [Lucas Rego](https://github.com/lucasraziel)
Twitter/X: [Lucas Rego](https://twitter.com/lucasraziel)
Project Url: [rinha-de-backend](https://github.com/lucasraziel/rinha-de-backend )
- Node using [Fastify](https://fastify.dev/)
- MongoDB
- Redis

lucasraziel

---

participantes/giovannibassi/README.md
participantes/giovannibassi/ddl.sql
participantes/giovannibassi/docker-compose.yml
participantes/giovannibassi/nginx.conf

Com emoção, faltando 3 minutos, senão não tem graça.

Adiciona Giovanni

---

participantes/saiintbrisson/docker-compose.yml
participantes/saiintbrisson/init.sql
participantes/saiintbrisson/nginx.conf

Adds my participation project, hosted on https://github.com/saiintbrisson/rinha-de-backend-2023-q3

feat: add saiintbrisson

---

participantes/grupo-2a/README.md
participantes/grupo-2a/ddl.sql
participantes/grupo-2a/docker-compose.yml
participantes/grupo-2a/nginx.conf
participantes/grupo-2a/run.sh

Excelente desafio, mal posso esperar para o q4.

inscrição andr3marra

---

participantes/wendryo/README.md
participantes/wendryo/docker-compose.yml
participantes/wendryo/nginx.conf

Desculpa o atraso de minutos, problema com o docker hub. Não tava conseguindo dar o push na imagem. Aceita ai plz

Adição participante wendryo
